export const classes = {
  wizard: {
    name: 'Wizard',
    description: 'Master of arcane magic.',
    modifiers: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 2,
      wisdom: 1,
      charisma: 1,
    },
    hitPoints: 6,
    armorClass: 10,
    startingSkills: ['Arcana', 'History'],
  },
  warrior: {
    name: 'Warrior',
    description: 'Mighty warrior skilled in combat.',
    modifiers: {
      strength: 2,
      dexterity: 0,
      constitution: 2,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
    },
    hitPoints: 10,
    armorClass: 14,
    startingSkills: ['Athletics', 'Intimidation'],
  },
  thief: {
    name: 'Thief',
    description: 'Stealthy rogue skilled in deception.',
    modifiers: {
      strength: 0,
      dexterity: 2,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 2,
    },
    hitPoints: 8,
    armorClass: 12,
    startingSkills: ['Stealth', 'Sleight of Hand'],
  },
  ranger: {
    name: 'Ranger',
    description: 'Skilled hunter and tracker of the wild.',
    modifiers: {
      strength: 1,
      dexterity: 1,
      constitution: 0,
      intelligence: 0,
      wisdom: 2,
      charisma: 0,
    },
    hitPoints: 8,
    armorClass: 13,
    startingSkills: ['Survival', 'Nature'],
  },
};
